prometheus:
  <<: *metrics
  image: prom/prometheus:latest
  container_name: prometheus
  user: $PUID:$PGID
  ports:
    - 9090:9090
  command:
    - "--config.file=/etc/prometheus/config.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    - "--web.enable-lifecycle"
    - "--web.enable-admin-api"
  volumes:
    - $DOCKERDIR/appdata/prometheus/config:/etc/prometheus
    - $DOCKERDIR/appdata/prometheus/data:/prometheus
  environment:
    <<: *user