---
version: "3.9"
x-environment: &user
  PGID: $PGID
  PUID: $PUID
  TZ: $TZ
x-root: &root
  PGID: $ROOT
  PUID: $ROOT
  TZ: $TZ
x-common: &common
  security_opt:
    - no-new-privileges:true
  restart: always
x-core: &core
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
x-media: &media
  network_mode: host
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      <<: *user
    volumes:
      - $DOCKERDIR/appdata/beets:/config
      - $MUSIC:/music
      - $BLACKHOLE:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped
  daapd:
    image: lscr.io/linuxserver/daapd:latest
    container_name: daapd
    network_mode: host
    environment:
      <<: *user
    volumes:
      - $DOCKERDIR/appdata/daapd:/config
      - $MUSIC:/music
    restart: unless-stopped
  docker-gc:
    <<: *common
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      CRON: 0 0 0 * * ? # ED @ 12:00am
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      TZ: $TZ
  dozzle:
    <<: *common
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8080:8080
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label.
      # DOCKER_HOST: tcp://socket-proxy:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  filebrowser:
    <<: *common
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - 82:80
    volumes:
      - $DOCKERDIR/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - $DOCKERDIR/appdata/filebrowser/settings.json:/config/settings.json
      - $USERDIR:/srv
    environment:
      <<: *root
  mstream:
    image: lscr.io/linuxserver/mstream:latest
    container_name: mstream
    environment:
      <<: *user
      UMASK_SET: 002
    volumes:
      - $DOCKERDIR/appdata/mstream:/config
      - $MUSIC:/music
    ports:
      - 3000:3000
    restart: unless-stopped
  plex:
    <<: *media
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    volumes:
      - $PLEX_DATA:/config
      - $MOVIES:/movies
      - $TV:/tv
    environment:
      <<: *user
      VERSION: docker
  plexmm:
    <<: *core
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plexmm
    volumes:
      - $DOCKERDIR/appdata/plex-meta-manager:/config
    environment:
      <<: *user
      PMM_CONFIG: /config/config.yml
      PMM_TIME: 03:00
      PMM_RUN: "True"
      PMM_TEST: "False"
      PMM_NO_MISSING: "False"
  stash:
    <<: *media
    image: stashapp/stash:latest
    container_name: stash
    ports:
      - 9999:9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      <<: *user
      UMASK_SET: 002
      STASH_STASH: /data/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/stash:/root/.stash
      - $STASH:/data
      - $STASH/metadata:/metadata
      - $STASH/cache:/cache
      - $STASH/blobs:/blobs
      - $STASH/generated:/generated
  tautulli:
    <<: *core
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8181:8181
    volumes:
      - $DOCKERDIR/appdata/tautulli:/config
      - $PLEX_DATA/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      <<: *user
  watchtower:
    <<: *common
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_NO_STARTUP_MESSAGE: false
      WATCHTOWER_SCHEDULE: "0 30 12 * * *" # ED @ 12:30am
      DOCKER_API_VERSION: "1.40"
